# Generated by Django 4.1.2 on 2022-12-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=2000)),
                ('department', models.CharField(max_length=30)),
                ('student', models.CharField(max_length=30)),
                ('issolved', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
